# Generated by Django 3.2.5 on 2021-12-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('getuser', '0004_alter_user_isadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('project_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('partners', models.CharField(max_length=45)),
                ('details', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.IntegerField()),
                ('participants_id', models.ManyToManyField(blank=True, null=True, to='getuser.User')),
            ],
        ),
    ]
