# Generated by Django 3.2.5 on 2021-12-08 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getuser', '0004_alter_user_isadmin'),
        ('getproject', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Project',
        ),
    ]
