# Generated by Django 3.2.5 on 2021-12-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getuser', '0002_rename_id_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
