# Generated by Django 3.2.5 on 2021-12-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getproject', '0002_rename_student_project'),
        ('getuser', '0004_alter_user_isadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined_projects',
            field=models.ManyToManyField(blank=True, null=True, to='getproject.Project'),
        ),
    ]
