# Generated by Django 3.2.5 on 2021-12-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getproject', '0003_alter_project_participants_id'),
        ('getuser', '0005_user_joined_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_projects',
            field=models.ManyToManyField(blank=True, to='getproject.Project'),
        ),
    ]
