# Generated by Django 3.2.5 on 2021-12-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makechart', '0002_rename_gpu_gpus'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='ranks',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
