# Generated by Django 3.2.5 on 2021-12-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makechart', '0003_student_ranks'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('gpu_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('tpe', models.CharField(max_length=45)),
                ('location', models.CharField(max_length=45)),
                ('vendor', models.CharField(max_length=45)),
            ],
        ),
        migrations.DeleteModel(
            name='GPUS',
        ),
    ]
