# Generated by Django 3.2.5 on 2021-12-08 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('getuser', '0004_alter_user_isadmin'),
        ('makechart', '0004_auto_20211209_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='gpu_users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='getuser.user'),
        ),
    ]
